Put tatu back to new connection for each requisition.             # Heeded due to bug #-123 described in thread.py...             # File "/home/davi/git/oka-repository/backend/app/api/posts.py", line 319, in get             #     for m in data.Yt[0]:             # AttributeError: 'NoneType' object has no attribute 'Yt'
            [which means that mysql is returning old values] probably a problem with dangling cursorsor commit